apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: master-db
          image: postgres:12.20-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata: pg-service
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      pargetPort: 5432