Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-24.04'
  config.vm.box_check_update = false
  config.vm.define 'osman-master-node'
  config.vm.hostname = 'osman-master-node'
  config.vm.network 'private_network', ip: '192.168.56.110'
  config.vm.provider 'vmware_fusion' do |vmware|
    vmware.cpus = 2
    vmware.memory = 2048
  end
  config.vm.provision 'shell', path: 'script.sh'
end